rootProject.name = "Kore-Bindings"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

include(":core")
include(":test")
include("smithed")
include("smithed:crafter")
include("smithed:actionbar")
include("smithed:custom-block")
include("smithed:prevent-aggression")
include("bookshelf")
include("bookshelf:biome")
include("bookshelf:bitwise")
include("bookshelf:block")
include("bookshelf:color")
include("bookshelf:health")
include("bookshelf:hitbox")
include("bookshelf:id")
// include("bookshelf:link")
// include("bookshelf:move")
// include("bookshelf:math")
// include("bookshelf:position")
// include("bookshelf:raycast")
// include("bookshelf:schedule")
// include("bookshelf:sidebar")
// include("bookshelf:time")
// include("bookshelf:tree")
// include("bookshelf:vector")
// include("bookshelf:view")
// include("bookshelf:weather")
// include("bookshelf:xp")
include(":energy")
include(":item-io")
// include(":furnace-nbt-recipes")
// include(":smart-ore-generation")
include(":load")
include("generation")
